/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import java.io.IOException;
import java.util.List;

import project.dto.TotalDto;
import project.utils.JsonMapperUtils;
import project.utils.FileUtils;

public class App {

    private static final String PROBLEM_1_PATH = "problem_1.json";
    private static final String PROBLEM_2_PATH = "problem_2.json";
    private static final String BASE_DIR_PATH = "data/output";

    public static void main(String[] args) throws IOException {
        System.out.println("Hello world");

        // 아래에 문제 해결을 위한 코드를 작성해주세요.
        CustomerService service = new CustomerService();

        // problem 1
        int totalCount = service.getTotalCustomerCount();
        TotalDto answer1 = new TotalDto();
        answer1.setTotal(totalCount);
        solve(answer1, PROBLEM_1_PATH);

        // problem 2
        List<Integer> answer2 = service.getDormantCustomerIds();
        solve(answer2, PROBLEM_2_PATH);
    }

    private static <T> void solve(T answer, String filePath) throws IOException {
        String jsonAnswer = JsonMapperUtils.converToJson(answer);
        FileUtils.writeToFile(BASE_DIR_PATH, filePath, jsonAnswer);
    }
}
